title: Default Page
preset: page
pages: false
fields:
  description:
    label: Description
    type: textarea
    width: 1
  image:
    label: Project Image
    type: files
    min: 1
    max: 1
    width: 1

